[package]
name = "panic-rtt-target"
description = "Logs panic messages over RTT using rtt-target"
version = "0.1.2"
edition = "2018"
readme = "README.md"
keywords = ["no-std", "embedded", "debugging", "rtt"]
license = "MIT"
license-file = "../LICENSE"
authors = ["Matti Virkkunen <mvirkkunen@gmail.com>"]
repository = "https://github.com/probe-rs/rtt-target"

[dependencies]
rtt-target = "0.4.0"

# Platform specific stuff
cortex-m = { version = "0.7.1", optional = true }
# riscv = { verison = "0.10.1", optional = true }
critical-section = "1.1.1"

[features]
cortex-m = ["dep:cortex-m"]
#riscv = ["dep:riscv"]
riscv = []

[package.metadata.docs.rs]
features = ["cortex-m", "riscv"]
